version: '3.7'

services:
  api:
    build:
      context: .
    container_name: ${APP_NAME}
    image: ${APP_NAME}:latest
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"  
